spring.application.name=SpringkafkaProducerApp

#Server port
server.port=8888

#creating a topic
my.topic.name=NK-Skills

#kafa connection as producer details
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
